Software Requirements Analysis and Specifications/SportArete-master/SportArete/Controllers/BrandController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SportArete.Core.Contracts;
using SportArete.Core.Data;
using SportArete.Core.Models.Brand;
using SportArete.Core.Models.Product;

namespace SportArete.Controllers
{
    /// <summary>
    /// The controller is responsible for brand management.
    /// </summary>
    [Authorize]
    public class BrandController : Controller
    {
        private readonly IProductService productService;
        private readonly IBrandService brandService;

        public BrandController(
            IProductService _productService,
            IBrandService _brandService)
        {
            productService = _productService;
            brandService = _brandService;
        }

        /// <summary>
        /// Shows all available brands.
        /// </summary>
        /// <returns>Page with all brands.</returns>
        [AllowAnonymous]
        public async Task <IActionResult> Index()
        {
            var model = await productService.GetBrandsAsync();

            return View(model);
        }

    }
}

Software Requirements Analysis and Specifications/SportArete-master/SportArete/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SportArete.Core.Contracts;
using SportArete.Core.Data;
using SportArete.Core.Models.Product;
using SportArete.Core.Services;
using SportArete.Infrastructure.Data.Common;
using SportArete.Infrastructure.Data.Models;
using System.Security.Claims;

namespace SportArete.Controllers
{
    /// <summary>
    /// The controller is responsible for cart management.
    /// </summary>
    [Authorize]
    public class CartController : Controller
    {

        private readonly ApplicationDbContext context;
        private readonly IRepository repo;
        private readonly ICartService cartService;
        private readonly UserManager<User> userManager;

        public CartController(
            ICartService _cartService,
            ApplicationDbContext _context,
            IRepository _repo,
            UserManager<User> _userManager)
        {
            cartService = _cartService;
            context = _context;
            repo = _repo;
            userManager = _userManager;
        }

        /// <summary>
        /// Method for adding a product to the cart.
        /// </summary>
        /// <param name="productId">Product's id.</param>
        /// <returns>Adds a product to the user's cart.</returns>
        [HttpPost]
        public async Task<IActionResult> Add(int productId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!context.Carts.Any(c => c.UserId == userId))
            {
                await cartService.CreateCartForUser(userId);
            }

            Cart cart = await repo.All<Cart>()
                .FirstOrDefaultAsync(c => c.UserId == userId);

            var cartProducts = repo.AllReadonly<CartProduct>().Where(c => c.CartId == cart.Id);

            if (cartProducts.Any(cp => cp.ProductId == productId))
            {
                return RedirectToAction(nameof(MyCart));
            }
            await cartService.AddToCartAsync(userId, productId);

            return RedirectToAction(nameof(MyCart));
        }

        /// <summary>
        /// Opens the user's cart.
        /// </summary>
        /// <returns>Page of the user's cart.</returns>
        [HttpGet]
        public async Task<IActionResult> MyCart()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!context.Carts.Any(c => c.UserId == userId))
            {
                await cartService.CreateCartForUser(userId);
            }

            var model = await cartService.GetAllAsync(userId);

            return View(model);
        }

        /// <summary>
        /// Removes a given product from the cart.
        /// </summary>
        /// <param name="productId">Product's id</param>
        /// <returns>Removes a selected product from the cart.</returns>
        [HttpPost]
        public async Task<IActionResult> Remove(int productId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            await cartService.RemoveFromCartAsync(userId, productId);

            return RedirectToAction(nameof(MyCart));
        }
    }
}

Software Requirements Analysis and Specifications/SportArete-master/SportArete/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SportArete.Core.Contracts;
using SportArete.Core.Data;
using SportArete.Core.Models.Order;
using SportArete.Core.Services;
using SportArete.Infrastructure.Data.Common;
using SportArete.Infrastructure.Data.Models;
using System.Security.Claims;

namespace SportArete.Controllers
{
    /// <summary>
    /// The controller is responsible for order management.
    /// </summary>
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly IRepository repo;
        private readonly IOrderService orderService;
        private readonly ICartService cartService;
        private readonly UserManager<User> userManager;

        public OrderController(
            IOrderService _orderService,
            ApplicationDbContext _context,
            IRepository _repo,
            UserManager<User> _userManager,
            ICartService _cartService)
        {
            orderService = _orderService;
            context = _context;
            repo = _repo;
            userManager = _userManager;
            cartService = _cartService;
        }

        /// <summary>
        /// Creates a new order which will be filled with user's delivery information.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!cartService.AnyProducts(userId))
            {
                return RedirectToAction("Index", "Home");
            }


            var productsIds = orderService.GetAllProductIds(userId);

            var model = new AddOrderViewModel();

            return View(model);
        }

        /// <summary>
        /// The user fills his delivery information and sends it to the database.
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> Create(AddOrderViewModel addOrderViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(addOrderViewModel);
            }

            try
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                await orderService.AddOrderAsync(addOrderViewModel, userId);

                return RedirectToAction("Index", "Home");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Something went wrong");

                return View(addOrderViewModel);
            }

        }

        /// <summary>
        /// Page with all orders of a given user.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> Mine()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var model = await orderService.Mine(userId);

            return View(model);
        }

        /// <summary>
        /// Method to confirm that a given order was delivered.
        /// </summary>
        /// <param name="orderId"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Confirm(int orderId)
        {
            bool result = await orderService.Confirm(orderId);

            return RedirectToAction(nameof(Mine));
        }
    }
}

Software Requirements Analysis and Specifications/SportArete-master/SportArete/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SportArete.Core.Contracts;
using SportArete.Core.Data;
using SportArete.Core.Models.Product;
using SportArete.Core.Models.Review;
using SportArete.Infrastructure.Data.Models;
using System.Security.Claims;

namespace SportArete.Controllers
{
    /// <summary>
    /// The controller is responsible for product management.
    /// </summary>
    [Authorize]
    public class ProductController : Controller
    {

        private readonly ApplicationDbContext context;
        private readonly IProductService productService;
        private readonly IReviewService reviewService;
        private readonly IUserService userService;

        public ProductController(
            IProductService _productService,
            ApplicationDbContext _context,
            IReviewService _reviewService,
            IUserService _userService)
        {
            productService = _productService;
            context = _context;
            reviewService = _reviewService;
            userService = _userService;
        }

        /// <summary>
        /// Method for getting all available products
        /// </summary>
        /// <returns>All available products</returns>
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> All()
        {
            var model = await productService.GetAllAsync();

            return View(model);
        }

        /// <summary>
        /// Method for adding a review.
        /// </summary>
        /// <param name="id">Id of the product</param>
        /// <returns>View to fill a review form.</returns>
        [HttpGet]
        public async Task<IActionResult> AddReview(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var model = new AddReviewViewModel()
            {
                ProductId = id,
                UserId = userId
            };

            return View(model);
        }

        /// <summary>
        /// Method for adding a review.
        /// </summary>
        /// <param name="addReviewViewModel">A DTO filled with data.</param>
        /// <returns>Adds a review to the product and returns the user to the index page.</returns>
        [HttpPost]
        public async Task<IActionResult> AddReview(AddReviewViewModel addReviewViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(addReviewViewModel);
            }

            try
            {
                await reviewService.AddReviewAsync(addReviewViewModel);

                return RedirectToAction("Index", "Home");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Something went wrong");

                return View(addReviewViewModel);
            }
        }

        /// <summary>
        /// Method for showing all the information of a product.
        /// </summary>
        /// <param name="id">Product's id.</param>
        /// <returns>Product's page.</returns>
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Detail(int id)
        {
            Product viewedProduct = await context.Products
                .Where(p => p.Id == id)
                .FirstOrDefaultAsync();
            viewedProduct.ViewsCount++;

            await context.SaveChangesAsync();

            var reviews = reviewService.GetProductReviews(id)
                .Select(x => new ReviewViewModel()
                {
                    Id = x.Id,
                    Comment = x.Comment,
                    Rating = x.Rating,
                    ProductId = x.ProductId,
                    UserId = x.UserId,
                    UserName = userService.GetUserNameById(x.UserId)
                }).ToList();

            var product = await context.Products
                .Where(p => p.Id == id)
                .Select(p => new DetailedProductViewModel()
                {
                    Id = p.Id,
                    Model = p.Model,
                    Description = p.Description,
                    Size = p.Size,
                    Price = p.Price,
                    ImageData = p.ImageData,
                    Category = p.Category.Name,
                    Brand = p.Brand.Name,
                    Reviews = reviews
                }).FirstOrDefaultAsync();


            if (product != null)
            {
                return View(product);
            }

            return RedirectToAction("All", "Products");
        }

        /// <summary>
        /// Shows all products of a certain brand.
        /// </summary>
        /// <param name="brandId">Brand's Id.</param>
        /// <returns>Page with products of a certain brand.</returns>
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Brand(int brandId)
        {
            var model = await productService.GetAllByBrandAsync(brandId);

            return View(model);
        }

        /// <summary>
        /// Shows all products of a certain category.
        /// </summary>
        /// <param name="brandId">Category's Id.</param>
        /// <returns>Page with products of a certain category.</returns>
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Category(int categoryId)
        {
            var model = await productService.GetAllByCategoryAsync(categoryId);

            return View(model);
        }
    }
}

Software Requirements Analysis and Specifications/SportArete-master/SportArete/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SportArete</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SportArete.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/ProductSliderCSS.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/card.css" asp-append-version="true" />

    <style>
        .nav-l1 {
            font-variant: all-small-caps;
            color: black;
        }
       
        .nav-l1:hover{
            border-bottom:solid;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SportArete</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item nav-l1">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="All">Browse all products</a>
                        </li>
                        <li class="nav-item nav-l1">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Brand" asp-action="Index">Brands</a>
                        </li>
                        <li class="nav-item nav-l1">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                    </ul>
                    
                    @if(User.Identity.IsAuthenticated)
                    {
                        <ul class="nav-item nav-l1">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Mine">My orders</a>
                        </ul>
                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="nav-item nav-l1">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="MyCart">
                                <img src="https://media.istockphoto.com/id/1206806317/vector/shopping-cart-icon-isolated-on-white-background.jpg?s=170667a&w=0&k=20&c=jFgoM27NKwD5xbu6U9gkOwlIKc1L82PlFDYlcIJwi8E="
                                 alt="Cart logo" width="30" height="30">
                            </a>
                        </ul>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
   @* <div class="container">*@
        <main role="main" class="pb-3">

            @RenderBody()
        </main>
@*   </div>*@
@*
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SportArete - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/ProductSliderJS.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>